### ISSUE TITLE
Use Fixes from ValveSoftware/halflife/issues/2495

### ISSUE THREAD

**Issue by ccuntd** [FWGS/hlsdk-portable#172]
https://github.com/ValveSoftware/halflife/issues/2495
includes nice animation fixes also in code!
look at it!

**Comment by nekonomicon** [comment]
It can break timers in multiplayer if you have vanilla server and modified client.

**Comment by hiIexistlol** [comment]
you could add it to simple mod hacks or so

**Comment by hiIexistlol** [comment]
like you currently have with like the crowbar fix

**Comment by MrSwedish** [comment]
yea, can we have it?
