### ISSUE TITLE
Tau-cannon sometimes produces two beams and two decals

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#256]
Start charging gauss secondary attack and immediately stop, making it shoot. There's a high chance you'll see two beams and two gunshot decals will be left on the wall.

[StartFire](https://github.com/FWGS/hlsdk-xash3d/blob/master/dlls/gauss.cpp#L571) gets called two times on the client for some reason.

The issue is observed in the Steam Half-Life too.

**Comment by SNMetamorph** [comment]
https://hlfx.ru/forum/showthread.php?s=&threadid=5269

**Comment by FreeSlave** [comment]
We had a fix for attack time https://github.com/FWGS/hlsdk-xash3d/commit/0e251e6f095514b3b27a0d99b2217dab09d6b612
Or is there something else that should be fixed?

**Comment by SNMetamorph** [comment]
> Or is there something else that should be fixed?

I guess yes

**Comment by FreeSlave** [comment]
If this patch is applied https://github.com/SamVanheer/halflife-updated/commit/8c26a9910923edb62dd796888b20d32853df118a there's no visible double beam anymore, because both generated beams use the same direction.

**Comment by nekonomicon** [comment]
Fixed in https://github.com/FWGS/hlsdk-portable/commit/d3dba792b109c008644620d345d867f847af86bb
