### ISSUE TITLE
Mobility API and physics interface under permissive license.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/hlsdk-portable#259]
Subj

**Comment by a1batross** [comment]
Like build.h, I want to relicense it to public domain.

**Comment by nekonomicon** [comment]
@a1batross any progress?

**Comment by a1batross** [comment]
@nekonomicon we didn't make physics/render API but for mobility API header I would like to request a permission from @mittorn and you, as you both contributed to it previously in old engine.

As for FOSS headers for HLSDK, I've started documenting API interfaces, so somebody else could rewrite them from scratch. As this process is iterative (I'm mostly cross-referencing Quake and Quake II sources as a base), it will at some point involve Xash's physics API too.

**Comment by nekonomicon** [comment]
> @nekonomicon we didn't make physics/render API but for mobility API header I would like to request a permission from @mittorn and you, as you both contributed to it previously in old engine.

I give my permission.

**Comment by mittorn** [comment]
I give my permission

**Comment by a1batross** [comment]
https://lists.sr.ht/~a1batross/xash3d-fwgs/%3C20240103045042.416609-1-a1ba.omarov%40gmail.com%3E

Not sure if we actually should go with Unlicense for that. I don't think anyone will ever complain but some people disagree and recommend CC-0 over it: https://fedoraproject.org/wiki/Licensing/Unlicense

**Comment by nekonomicon** [comment]
I've heard public domain software are prohibited by law in some countries or something like that.
Possible alternative: https://opensource.org/license/0bsd/

**Comment by SNMetamorph** [comment]
> I've heard public domain software are prohibited by law in some countries or something like that. Possible alternative: https://opensource.org/license/0bsd/

I don't think that we should care about that bureaucracy absurd

**Comment by a1batross** [comment]
> > I've heard public domain software are prohibited by law in some countries or something like that. Possible alternative: https://opensource.org/license/0bsd/
> 
> I don't think that we should care about that bureaucracy absurd

That's what I meant when I said "nobody will ever complain".

Permissive license actually is fine too. I think picking 2-clause BSD would be enough, it's a popular and proven choice. It only requires attribution, but the whole purpose here is just allow inclusion in HLSDK.

**Comment by nekonomicon** [comment]
Bump.

**Comment by a1batross** [comment]
Mobile api header already relicensed under Unlicense in engine repo. I don't think we have anything else that's easily relicensable.

**Comment by nekonomicon** [comment]
What about SDK?

**Comment by a1batross** [comment]
SDK for what?

We're still using HLSDK headers and I didn't finished writing documentation
for HLSDK structs.


вс, 21 июл. 2024 г., 22:05 Andrey Akhmichin ***@***.***>:

**Comment by nekonomicon** [comment]
When you update mobility api header in hlsdk-portable?
Issue about that.
