### ISSUE TITLE
Platform checks are slow on Windows

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#265]
Not a bug, just a noticeable inconvenience.
Platform checks during the project configuration (`Looking for XASH_...`) are much slower on Windows than on Linux.

**Comment by SNMetamorph** [comment]
Same problem in PrimeXT

**Comment by nekonomicon** [comment]
CMake already has internal checks for different platforms, so may be not good idea to check every symbol in build.h.

**Comment by a1batross** [comment]
> CMake already has internal checks for different platforms, so may be not good idea to check every symbol in build.h.

No it doesn't. You can't get target processor just from CMake.

CMake also could have multithreaded checks but it doesn't.

**Comment by a1batross** [comment]
I wish we could just get all defined macros on MSVC, as we can do on GCC or Clang. But the needed feature was only added in [only recent MSVC](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCBmAOwapAAOqAqETgwe3r56KWmOAkEh4SxRMfGJdpgOGUIETMQEWT5%2BXLaY9gUMdQ0ERWGR0bEJtvWNzTltCmN9wQOlQxUAlLaoXsTI7BwA9ABUJhoAghFedOgAdAgA1AC0V2gsSXSYN45sVydnV8H8xCxMXQOhyBABUEHgFN9IVRiJhMFdDOgrl4QgxkINYUiFKgqAQAO4NeGw%2BhMJRI4JEK4EBDwpJeCK0PDIK7oVD/YLnIFAw4MACeAnhEKuMLhVNQ91QSV5pCuLAweCo0qudIZEIQMq8ShlDye9BldloMpIQPw02IeBOBHh1KF2NxBNhMswhBpxG%2BDCu2PWmwlWGFJBYVxICMhTAlj2e6CBEWCDSVvwRfOV6zymG1bLYGzwYiDboYAhuD0zyGzhsTSIivMTvKBbEMCk5RyBAEkPdp1hD8DUBJDqQCrrC0MAGHgAF7wtBS83ABAEK4GPEKGXU%2BFMLzU4PBtcb4gKIE4qngyF2/GElmYLsA1dJxEI2i0CVTvAzucU6KYabuw%2BYIEnh3W8UV2TVVmVZdkGHOK4AHV4X%2BABra0j3PS8un9N0gKiEIaAIfcqG/YDGWZfsDGIYBryRSkgKwAhzTYQQgzwtY3RpPBd3LX8vGQTYFGxXdIJg90rQYCikKwFCMjFD5ryDAA3aI5yYBwGKBYlggAR1OBQEDo18PSSaJ9IIU4CCrA8xAfJJYSUejbyodd1iJZ9Z17QCj1/HFT1hZFhOiR9eWnWd5yYPFG2BI4QQACWwK4hAAeQAMRBKDDgAJWi5shCuZQUtigA1ZsABFsAKq5zDMQ5MoysqZSg5tItiuQQWg1KUsOUIQQATSuBKrjarqAGlm1CArSCBbAAA1suwIRMtilKrmbABZZQAmbYqZSGtwAjkAqhoAcSuCxGquUJYqa1bFrq4qrhBWKbqi5qUta9q1tm%2BKgUW7AUrcCK2pBQ4LGbVbOpleK6tCabMviubeqy1KQWbNw5ACVKsrkFLlFioRorakrTtCIb4pS/bsE%2B9rQqGk67uwXLsHamLfoCAJ7pxxqIrmzKLGi1aAYCaLofmvqri2w4lplArDkWw49um7qUqBM6ovmnnAeBjqaqiyKvoW0Jet1w43AR2LdZ6txjZBVrDZlW6UqamHFa%2B2rsdGo5Uoy/ariJ2LFplBq7fiuWdeF42IcN5tjeguqIpZmKEqS1LophrWrjkbG5YVrX5qKw5VtCPbKt15O4sS5K0tCoF4uDOUvJ%2BAMAQyGUkhJJQB0wKhfMpEwAGY3FnAgkhAbZthRQjGCUc4SGAbZu%2BwIFdmnpszC7yymGAf4gzRH9F67hUfLwo6gYKgB9CKuSXrAaBCQ65EPk%2BuSOIfevvK5xoqiKj92WVFOIVJPUwOdKyHiFDSJgWA3RnmAF4BohgrQXkkggJgcllSpHSEgmSYgvDwlQCuYgeIITwnzHOC%2BcwoxNgftsXqSYQh4nPJfWCmoAHwhRMQkISJ%2Bw0F3DhchVwOprHuIYK4ZEQjECvKVJezC27zghIw2gqAaF4OpEAyEApGTCJAECR%2BVwrgABJ%2BEANOLQC41wTBxDcH/JEYAOAKGngAVjcAQIewBLGlVMYI2ESQriWJMDY2e5825zBfm/ZxJizHBTgp4jgJiLDKnNPRbRZgXEFWCa43ic4QneTwGpFxoS8ThK8XEaJlkKRiLMOYLuEi8JlR0VwRJXjyEaIoUIcUwQrjoPNGsSEnxDEKGQOaJIBBIT8i8Pwj0wB3FoVKj4spFTAlCGjreKoSkBC0CrEoNAwkrh4hIKQw4j9gwtMMNg10G8OhzBiA0rROi9EfAMUY7JbjMAeK8VM8Re9ZkRWSTkvJkSCkxOKfE2pkSyHAleRfd5R8ABskhAYgjPuUt5r85lH0lgVKFcKZmIvfrjHKhV0UIrfsi5QK1Z7bwxQS1Ki08VgsxcilKi0T6pQKvFZQVLJE0opUfYuIJmWsrwuyulMlJC8vBRSmSNjhX8sWjJCFEryUCriLKpFoqAAcir36Az2kfOmu02pqqPhYIQBU9UFSxpIPaUE9XYDMP1S1i0hBuGJsoEEdM9VE2wNgA1RrSX4qRb9Zs/U5B6vDkIPVAApEN3rqUEtznIcaergYgj5lq4azZdWRrZQSy6ecLXpr5Zm5sygI0gvhVGpFRK3B6sWrFVW2Aj4rUONyualLc3grtblCtLaaUQxBJ6vVsVlB017Z2glmMhDNjjcOpFxN7W5T1dOtwuUj4mrkBYPmPLJ3v3nYusdec10so3UfLdnK47ruLWSpF2M0oE06nq2qoQu6lIPXetFB7xrKplcCoe3cjVdx/X%2B79AHf2Af/UB0DIHwPAcg2BqDEHoNwdgwhmDSH4PIcQyh9DEH6ncMuThy5/avoNo9kIDqQhnWLSuEVMGEMi1fvqRh1DDH6NMbQyxxjrHmNsc4xx7jXri0KloSQiAR870PqWPfAAnGUlh8IaUiYSVwCTZT%2BPSfQEJo%2BWbzUPqPkfMTZDJMaEk34uhrb9pQSuApvTZTTl4RU0Ju1bgj60xSrpsK%2BnDNd2k62oQ7bzOKaXq4BU99XNKZs/41hQnn2SBcwcNzUmwsyYJZF3zln/PCUC9vazAnwvadUV4VQ2nosGbi8ZmlMbxrJeC0vZT8XVPaexbFQqBXFNFaMwE9lw0cUlQs5VruAW8KP1s3VjrDXj46b8x5%2BL4LR3joq1ZxkoW6G1cJcSprKWd5om8H6buhsGhkSaAIfAXQxANgQDPcbnn2VEr5rNlrO88L/RSjLEER8sZH2Dc19zF2CXBpu%2B5vrVxH4Paey9oQb2sbncmzS6b5Xutzeq4ttT8VYSYE9QV7J6TBtH1CP/VHOn0euMx7FfSDBceFc%2B5DglnrfshayxeRHyPScfeK21glbqPWGup/5%2BbtOlvY4IIzyzt2vtIu7VT2Ht3MuE%2BJwL4LQuKdIvw6EMX42%2BsQ5KyOrGM3Ydc/hyQq42nSb2sdc60I2m1cs6RYbh1BaTezZ1wtvX2nkogjNotBzR8xEyrMBCnn%2Bul2vaPubq%2BNKTVCDNWZ8X5P1dIoTUm7Vqbdba969zlTfu/UBrN2t4X7909yE5xN6P79od2%2BT7r1hfulCwhHCZTPPXs%2Bcq%2BnTOqXVI/M%2BDxrsdMO4UdCUN34gP83RlWUAYH0Qy3SSmiPXIwnpeTTEwIGZg7xXSYDAGABaeEbSQiFGGFg0imAIWXMQKslIaCqAlGlrooYIioCQbedxJAFI3OAGVbvaWqBBZp6n9rBVOv47MV/77cHLPeXd%2BKtGtOtFGRtOlEvVXT9aeHjLjdjJAxAlAhAtA5A9AzjLDXZChXDXDePNqajTKSjIaaaBpcgzAygjA6g1Amgqg2ghg6DYFT/GrCAGlAWNwWtWPWtAg0IJYT3cwH3WzdguaTg/VZsTVXgsnKzfvYMMqCwI5cFDgrguqRNHglNNqcsJQ0Q2tDVZNHVXWM8FTF/DLFPVgkQ76FQkENQ/QhPaQ1rdvGPVQuPDQxPbvMwhHCwsQvQqQoPBLJFHw1wmAt/D/KrPCVfYQ6NZw9Qgw/gwQwQzxMASIgIiQ2wtqewu7X3GlNtMxEJdJbTbgtI03QPQXcTIeVfCotfZQH%2BCIJgBkKscyaCYIemYIaYcyeuHsAcFELfD0RkAgAgegK4ALQwJnBw/w9%2BQo3g/PTLbTQIgw2vGLRYsY8FOYhPaYjwwTWYjqZ1F7FKIqFKNHeI73HnNTOafY8QyQ1ww473BIwnPYr6I%2BSYq4vHR%2BbEd4HUZ4NiTzTfUYzIrYnYs4h4j3YDP3QEg41YtqBYoraEqPC3dVVIqY1vCXbnf42tME7TUqMDUE%2B4g4p4%2BYko2XWLZY0raIoo6nZE3vUopY3rWQwfMwMwOQBgOCfMPED0YYhgEIHiVfEwwkqzEItbHvLeXkqrDbLwLbHuBQWfbYJIaBFgS4M7KksIv3CwbYtEnEzEv9ZUhE1wpnOXQvC4skpEv7FE/VVU3Y/YjU79P3PEhPXU2ExwiY0kxE34wUu0mQgfEpRk5kuRNktLQwTkhQbk%2Bkl0/knrf7R%2BVfWTIaB9V/fAd/OAxgugpMxMlM%2BgtM5MpgnAi5PAnDNwZQPPVKH6K6Q2dGaKEg6jcgujDM6s1Mms9M2shslDbeMvOnbTVQd9SFSQQ40xDHVg9TI%2BcaKFDI%2BvKFGFfPevFFKFGAjY7LI%2BPALuDsvHPIgnPst9CFJcnslchHfs8dd9YckAgc99aclspEbTJgBoZABAKFDE5c//GrfXelClF9OvA80cuqccg8ilK4VVUwk8v3BoFgG8zcu8xbB82lZtHrfjOrOlWlH6S039b8v/P3DlQs9%2BZVKEokgvOE8C78lXE0lC76aOEEuIJC6Cx8wio%2BOIICitLcx3ci8jR%2BFgBQGSZkUQD0ZZBov4GSEilpB9D4QgX4ic6AhVAU/CmC1C%2BCkqH3W85C8Sii9c4E4C2S8in6SFUNDC6koS8jD9MMsSlSoirEmxUi8C2C9%2BGxDSvU7Cr88VUSqCkyiSkEyQYygi1SrsgkxYyyh0nCoVUSyk4Umkj0sqL0lkj0ClHk6k2AsKSCh3cvfssKxUgKuQ%2Bk0IcUKCYIRaVAGMQYlIRoK4Xkf%2BVfE6OECicUaiaIXfK%2BPEcES83qaAqgWRfsAGZsWUZi5kTUD8b4PCJgJIJuJkOo%2BgcKiXUM8bP87TLlZlai/Iky5QNwUHXKZlSSq4DQQSz8mC8a5QdYluR%2BMak9ZQCy%2B08Yky36PYha1vVLOMgHChHaxKCa9y%2B3X3bTXfJIBQDS4k/NQtY8mKuBbTFIPEAyZAV6rCry8tfPUao%2BX6/6689ymEtvQ6t8pqM63rYa%2B61PA3ezY3OmQG%2BvcNT6h6o%2BTAMwOCLG186Fd8xG%2BvK1fqXG1Go%2Bc0HpGSPw8FLdUGvCbTOm5AGSI%2BVQegD0EE58jyg68FeG9Yuy9mzm7mxgRamM0ox%2Bc4OWvCvygW90pKhkpkkKq4edG4XKXqQGQav7YatbMGsWo%2Beq1AAEI%2BOovAI%2BE8Fa/Uo9dakWr6082miEDmk2hqggC2mMa24IYAAahK%2Bve2/aPdR2vG420282y2o%2BVkekf2/ywOjKBdf3FdEOxG10hK6IQK%2Bk4Kn0jWxOrW4UD2nW5sPWvkuM9wxWiXWkkpYfRSeEMfBEDYcEK0BwByK4RfeEZfQq5sDfJCbfWUPfA/KkI/SSU/c/Q7DIK/G/ciVuHKx/E4Z/YMjLA2vjJ2tgxLQ4eKJdbAZ1Q2YqTsmFOIm444iI8wgleG/c/U4WpPSKuFfjSVRan8l8/UlVXGh%2B4ixmyVbit%2BuVcjPmz%2B3%2B6VH%2BpVaAkEmy5%2BqygVIym%2B7nd%2BrEnyiBry0VJym%2Blesu/jR%2BA%2BAIY%2BU%2BI4DgFYWgTgGxXgPwDgLQUgVATgCtSwawT0JiH0MpHgUgAgTQfBlYOCEASQMwc4ZVb3CFfhgRwRuIfQTgSQEh1hihzgXgBQEARIFhsh/B0gOAWAGAKAVRiAJAD4%2BgMgCgCALRoYZAWgI%2BahI%2BB9PgOgK0XcSgCICRmMZgI/CRosRgAgWKBgFZCRrAf4IwcQBR0gfAQcRwOSGR3xzAVQaodcLYJht8Qh3xxkCIERI/DwLACRmiPAFgTgHgFYeq1eBQXKPATAPEInRgDJ3gfgQQEQMQdgKQGQQQRQFQdQXx3QMwfQQwYwawawfQC0GRyAFYSUS/TgbYbADa7YAALWQBAEskeR/m4l4gB2UAKmkY6GqC6BcGEgmFaFIECDmBKDKFyBQS6HWb2fyAyH6B2aGCmCWe7G6BmEOYuc6FqBmFOYxD0DaPGE8BaBecee2eea4BWC9A2CqeYeRxKYIaIfEd8coY4HbJ9yYpYtaS4HE3OCkCuAgDvWwH4IgGoasEsBlFwEICSq7jaGFjZF1F8jKTMCWF4Hka0CWBWBATAUoHYZAC7i7nOBZfZY5c5YhREY4DEdIHSZZbZc5eFZZe5dIfIchekdkeYdYZWGUcQBQBJc%2BPIEoH0ZiEMYRaPjMA0C4HMq8C7lMeaZoFoEsZkYgBsd8bsbjEcYzGcdcfcd8c8daZ8fIf8eWbwCCYkdCfCatBKfIEEA6AkbiYSd5CSa2HIdSfSe4EUeyeAFyfycKeJz9bKeEFEHEGqZTbqbUAkd0C7haaMBQHaZxbie6YgF6f6UnoGaGYBzGYmfcWmY/Fme2HmcWfuecAgFcFuc2eEieYWBiDaDyHSAEC7cHa6F7d2bufdYEB6DeeyA2cWS6BndmGKB%2BdGF6C7deeXfmAnb%2BfocBZojhBBZ5eIdIHFd4EhehZarhZkgRfOA0BRbRYxaxY6auDxaIDpMJZlA8AjG0bERZcpZlYUdpdIHpaGDLdIA4cFZFZFe5Zib5bPckY4ClbkdlaUfUc0aVe0ZVb0cw6GBYp6qPhvfEy1fQtyiEC4HXOI9UChXMZNeiDNYtfIatYcd8accEHtd5A8fn2dfDd4DdZqE9ZCbCfRF9ejf9atBifIeDbjDDZSdoiPdjfjYKaKdIaYZTYqfTekEzaUGzcab0AMALdMBoeLa6fgHLf6Z2GrdGfGcmcslQBmeDGbYWfaDbb8A7bWfecmG7fQHHfOeSH2YyBHYC8KG%2Bb7ZecucXZuc8/nYi4ed6F8/7bXdnY%2BamC%2BZXbC9%2BdWG9H3eBejdBY4BPYQ4vanNheZCI/ODMGVSuDI4o/OHExRefZxdfcOwJaJe/dJY/d%2BapdlaZag%2Bg85Z5fg4kcldsGlepbYZ5bMF4HSZsUSCK6kcA5pbQ/gHlY0ZADWH7nXGw7VdCFYC2GhZuCnOAC4iuEkCRYq94AvHxfNHQD0HU7Taqa09kCzYafIaadIDxBEQHjy%2BPfBYlc4FinXDpDnAPEvdK/hcReRdRdIKfdw4/Ype66A969Zdm40AhXiC7hsTMBsTiDMCkBsUG%2Bm%2BZdZf64G/m6Q9G5Q6A%2BW9gCQA2%2BB%2B27h927YE4AO6nMMdafMzO40Dvcu5a5u7u9kA08e5qfkB09e50GZY%2B6%2B6PZicK%2BG4B6B/XAYiuDB9aoh7vYfZh4a7h7/a7gA/G%2BA9A5iHA8g5R4fW911YhV1fE2x%2Babg7%2B/PYW5kap6W9W7p6V4IEZ5/eiGZ/25K/V/K%2B1b5%2Bu7wFu7aHu8qYkCe9qfF5zb0E%2B%2B6tl7BdPYV44EB825B7wmo6cvB6D6q5q4hTq5159864N565A8wFATA96%2B4fEwhTiC4Cb40GVRsWVUx67mkAd9T4hed7G4r5iam/5ZAFm57/%2B4p8N6ZZx6RbiFJ5ZZ5a7kd8Q8R5pfy6H/J5X4m7kl3AyE4aAA%3D%3D). 

And remember we still have to target WinXP...

**Comment by a1batross** [comment]
Just a quick thoughts.

What if build.h will be precompiled header? Will it fix slow checks? Though I don't see how CMake can leverage precompiled headers for CheckSymbolExists.

Script can also be redone so more probable checks done first and if they are true, no further checks are done. Many variables are mutually exclusive, like CPU arch and OS.

**Comment by FreeSlave** [comment]
Closing as solved by https://github.com/FWGS/hlsdk-portable/pull/368
