### ISSUE TITLE
Add a hlfixed branch

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#268]
In `master` branch we maintain the network compatibility with original Half-Life client and server (or at least we should, I've never tested it myself). That means that we can't enable some fixes in master, especially ones related to weapons.

My proposal: make a `hlfixed` branch (or choose some other name) with all those fixes turned on by default. This branch can "compete" with [halflife-updated](https://github.com/SamVanheer/halflife-updated). I say it in quotes because we actually use a lot of Sam Vanheer's fixes. But we have our own fixes and also some of the fixes that exist in halflife-updated were found and introduced by us independently before halflife-updated.

What should be included:
* All *fix* macros must be enabled by default (**CROWBAR_FIX_RAPID_CROWBAR** and others, **CROWBAR_IDLE_ANIM** too), just like they're enabled e.g. in bshift branch.
* Default values of some cvars should be adjusted (`satchelfix`, `explosionfix`, etc.)
* We can add `cl_viewroll` and modify `cl_viewbob` behavior.
* Apply fixes to weapon animation times as requiested in https://github.com/FWGS/hlsdk-xash3d/issues/172 
* Any other fixes that were not included in this sdk yet for network or save/restore compatibility reasons.

**Comment by nekonomicon** [comment]
Branch [hlfixed](https://github.com/FWGS/hlsdk-portable/commits/hlfixed) was added.

> We can add `cl_viewroll`

Xash3D already has cvars `sv_rollangle` and `sv_rollspeed`, so we can add new cvars only for GoldSrc.

**Comment by FreeSlave** [comment]
Closing. If anyone has suggestions for hlfixed branch make PR to hlfixed branch or create another issue.
