### ISSUE TITLE
Feasibility of supporting mingw in this repository

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#277]
Do we need to support building hlsdk with mingw compilers?

Do we need to test building with mingw in github workflow? We could keep the check but allow it to fail. Or remove it altogether so it won't consume the workflow time.

**Comment by nekonomicon** [comment]
Reasons to drop mingw support:
1. GoldSource does not support gcc mangling on windows.
2. mingw requires to link fat gcc runtime(libgcc_s.so and libstdc++).

But we need some solution for crosscompiling:
1. MSVC98 compiler can works under wine but generates ineffecient code.
2. clang can use headers and libraries from Windows SDK for crosscompiling, but I don't see simple solution to get this headers and libraries under *nix.

I tried to extract files from ISO image with Windows SDK via `7zip` and `cabextract`, but filenames of extracted files was corrupted.
And Windows SDK Installer under wine just crashes.

**Comment by FreeSlave** [comment]
Cross-compilation is another thing. For now we can rely on github workflow for compiling on other platform.

> MSVC98 compiler can works under wine but generates ineffecient code.
You mean the code produced by msvc6 is less optimized?
Btw we have `/debug` flag in compile.bat files. Probably needs to be changed to `/release`.

**Comment by nekonomicon** [comment]
Yep.
And add /DNDEBUG to disable asserts.

**Comment by FreeSlave** [comment]
Removed mingw in https://github.com/FWGS/hlsdk-portable/commit/bed35fe8d1c9f90c21f751cb8a44526f01783a26
