### ISSUE TITLE
Rare bug with decals

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#317]
![20220808232849_1](https://user-images.githubusercontent.com/5596503/183546829-c38257ff-5964-44f9-8138-ea7b6998f9b0.jpg)

Got a report of the decal bug that happened during playing Blue Shift (on GoldSource) with game libraries from this hlsdk.

We experienced the same bug during Field Intensity development, especially in the eponymous chapter "Field Intensity" (probably it's still present and may happen sometimes)
![sad2a2d0002](https://user-images.githubusercontent.com/5596503/183546836-db965620-be16-47b1-bc87-a14452025080.png)

Before I thought it's some problem with my mod (be it code or maps), but as we see it can happen on Blue Shift maps too.

The bug is hard to reproduce (at least I'm not aware how to reproduce it consistently). I also don't remember seeing this bug in any other mods that are not based on this hlsdk.
Could it be that the source of the problem is switching from double literals to floats?

**Comment by FreeSlave** [comment]
I asked more people, and it seems it's up to the map, not to the game code.

**Comment by a1batross** [comment]
Nor server nor client can't really control the shape of decal.

It's probably a bug somewhere inside the engine.

**Comment by FreeSlave** [comment]
Closing this as it's not an issue of hlsdk
