### ISSUE TITLE
how to build for (and while on) other architectures

### ISSUE THREAD

**Issue by yaktoma2007** [FWGS/hlsdk-portable#324]
How to build for (and while on) other architectures. (ARM, ARM64, PPC, PPC64, PPC64le, RISC-V)
more accessible build instructions for other architectures.

**Comment by a1batross** [comment]
You just do. There is no anything special.

**Comment by yaktoma2007** [comment]
> You just do. There is no anything special.

I meant this dependency-wise. Do i need the 32-bit ARM version of libsdl2-dev when compiling for ARM64? Or just the ARM64 version? Also which chroots can i use, or cant i use any chroots.

**Comment by nekonomicon** [comment]
SDL2 needed only for GoldSource(Actually i386 linux).
For different architectures you can set `64BIT` variable.
Instructions with chroots only for GoldSource modders/users.
For any other cases see `#Other platforms`.
