### ISSUE TITLE
NPCs ignore pit drones how to fix it 

### ISSUE THREAD

**Issue by Pandaprewmaster** [FWGS/hlsdk-portable#326]
Hello there so i been playing half life opposing force on phone okay? I got this issue of having NPCs not shooting pit drones now i only want friendly grunts to attack them since i have them with me most of the time using a spawner to spawn marines you normally leave behind since they cant get in vents jump etc here is how they treat pit drones
![Screenshot_20220916_173138_in celest xash3d hl](https://user-images.githubusercontent.com/113544864/190666515-b8fc3fd4-e702-440f-bb38-0d937061083d.jpg)
![Screenshot_20220916_173125_in celest xash3d hl](https://user-images.githubusercontent.com/113544864/190666550-30d8cd8d-32f3-45ea-9e56-1e80f48288e3.jpg)
![Screenshot_20220916_173104_in celest xash3d hl](https://user-images.githubusercontent.com/113544864/190666568-aee97cb4-76bf-4369-83e9-9c0051cc98c3.jpg)

My question is how to fix this? If you can edit the behavior of friendly grunts to shoot pit drones that be enough to help me then upload the file and give me it (: i will owe you a beer XD

**Comment by FreeSlave** [comment]
Hi. Where did you take Opposing From for Android from?
You're probably using the LostGamer's launcher or some other outdated version.

There's an issue with pitdrone relationship in our current opfor branch, indeed, but it's a different one - pitdrones won't attack barneys. I've made a PR to fix it https://github.com/FWGS/hlsdk-portable/pull/327

Anyways someone will have to make an updated Opposing Force launcher for Android and I'm not sure who's responsible for it. Especially considering that the new xash3d-fwgs engine is not quite ready for Android yet.

**Comment by Pandaprewmaster** [comment]
> Hi. Where did you take Opposing Force for Android from? You're probably using the LostGamer's launcher or some other outdated version.
> 
> There's an issue with pitdrone relationship in our current opfor branch, indeed, but it's a different one - pitdrones won't attack barneys. I've made a PR to fix it #327
> 
> Anyways someone will have to make an updated Opposing Force launcher for Android and I'm not sure who's responsible for it. Especially considering that the new xash3d-fwgs engine is not quite ready for Android yet.

Yes

**Comment by Pandaprewmaster** [comment]
![Screenshot_20220916_200516_ru zdevs zarchiver](https://user-images.githubusercontent.com/113544864/190692260-263b10f5-27a9-4da3-9a34-bbda131f2a41.jpg)

**Comment by Qwertyus3D** [comment]
I can confirm, that the old OF port by Hing has this issue with pitdrones. I checked updated OF dlls from [hlsdk-portable](https://github.com/FWGS/hlsdk-portable), and they seem to work properly. Regarding Android version we still need an updated OF APK to fix the problem.

**Comment by FreeSlave** [comment]
@nekonomicon can we just close this issue as it's clearly not an issue with this sdk, but with the one that was used to make the Android build?

**Comment by nekonomicon** [comment]
Sure.
