### ISSUE TITLE
Elevator bug in Blue Shift

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#330]
Running the `ba_elevator` map converted by BlueShiftBSPConverter on GoldSource. After player presses a button the elevator is getting stuck and damages player and a scientist.
Happens on both `master` and `bshift` branches.

**Comment by nekonomicon** [comment]
May be related:
https://github.com/FWGS/hlsdk-portable/commit/c041db99097241996d802fef42e5d4f28e549246

**Comment by FreeSlave** [comment]
Yes, deleting these lines fixes the bug. Why it was introduced in the first place? Why 0.05 is chosen as a number to compare to? Modifying it to 0.02 also fixes the problem.

**Comment by nekonomicon** [comment]
It was backported from Half-Life: Gravgun to prevent some bugs with elevators, but may be incorrect.

**Comment by FreeSlave** [comment]
Should we revert it completely? Maybe it should be left only for multiplayer or only for Xash3D?
If there's a reproducible case where `LinearMoveDone` is not getting called without these lines, we should somehow make it work in both cases.

**Comment by nekonomicon** [comment]
> Maybe it should be left only for multiplayer or only for Xash3D?
This fix for coop mode.

**Comment by nekonomicon** [comment]
Related fix in gravgun branch:
https://github.com/FWGS/hlsdk-portable/commit/7999455e9f9b73fb8c739b2cf864386a7f3466fe

**Comment by FreeSlave** [comment]
Then maybe it should have kept in gravgun branch, but not others.

**Comment by FreeSlave** [comment]
Fixed in https://github.com/FWGS/hlsdk-portable/pull/331
Closing
