### ISSUE TITLE
[MOD: They Hunger] Исчезает глушитель при использовании основной атаки +attack

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/hlsdk-portable#333]
Когда нажимаешь левую кнопку мыши ``+attack`` у глока исчезает глушитель.
А когда нажимаешь правую кнопку мыши ``+attack2`` у глока появляется глушитель, причём в обоих случаях воспроизводится звук стрельбы с глушителя.

Когда пистолет перезаряжается, у него также появляется глушитель.

Собирал библиотеки для They Hunger с этого репозитория.

Видео:
https://www.youtube.com/watch?v=DjhWgcB5TFM

**Comment by nekonomicon** [comment]
Возможно проблема появилась с последним мерджем.

**Comment by Vladislav4KZ** [comment]
> Возможно проблема появилась с последним мерджем.

Да, отревертил последний коммит и баг исчез.

**Comment by Vladislav4KZ** [comment]
> Да, отревертил последний коммит и баг исчез.

Но там заметил исчезновение глушителя после смены карты в одиночной игре.

**Comment by nekonomicon** [comment]
> Когда нажимаешь левую кнопку мыши +attack у глока исчезает глушитель.
А когда нажимаешь правую кнопку мыши +attack2 у глока появляется глушитель, причём в обоих случаях воспроизводится звук стрельбы с глушителя.

Исправлено.

> Но там заметил исчезновение глушителя после смены карты в одиночной игре.

Это вроде и с оригинальными dll воспроизводится, как и пропажа фильтра у снайперки.
