### ISSUE TITLE
Проблема при компиляции ветки bot 10

### ISSUE THREAD

**Issue by erfty125** [FWGS/hlsdk-portable#335]
я скопировал ветку и попытался её скомпилировать под armv7a hardfp и мне в input_mouse и input_goldsrc выдало ошибку мол не находит build.h . Скопировал build.h из public в cl_dll и скомпилировалось . потом отправлю ошибку и попробую собрать апк.

**Comment by nekonomicon** [comment]
А зачем собирать клиентку?
Тебе только содержимое dlls нужно.

**Comment by erfty125** [comment]
А то хорошо тогда закрываю issue

**Comment by erfty125** [comment]
Всё получилось , боты заспавнились только вот как на новый движок мод перенести

**Comment by Velaron** [comment]
ждать
