### ISSUE TITLE
Simplify build process by removing all sample and unused source files

### ISSUE THREAD

**Issue by a1batross** [FWGS/hlsdk-portable#366]
There goes:
* `GameStudioModelRenderer_Sample.cpp`
* `Wxdebug.cpp`
* `mpstubb.cpp`
* `stats.cpp`
* `prop.cpp`

Headers are harmless but still unused:
* `hud_servers_priv.h`
* `tf_defs.h`

**Comment by nekonomicon** [comment]
Incorrect list.
> mpstubb.cpp

Needed for multiplayer mods.
> prop.cpp

Needed for gravgun branch.

> tf_defs.h

used in Velaron's tf15client.

Also, you forgot about:
 - `h_cine.cpp`
 - `tempmonster.cpp`
 - `spectator.cpp`
 - `spectator.h`

**Comment by a1batross** [comment]
I filtered all source files.
These files are not used on master branch. It makes no sense to keep
prop.cpp here, since it already included on it's own branch.

Same for mpstubb. h_cine and tempmonster are being added, though I'm not
sure that original Valve project files include them.


вс, 16 апр. 2023 г., 08:01 nekonomicon ***@***.***>:

**Comment by a1batross** [comment]
Also to make it even more easier for us, some files could have macros toggling if the whole file should be compiled or not.

Like what we did on old engine, if something don't need to be compiled, it can have simple preprocessor check at the beginning of the file, with #endif in the end.

**Comment by nekonomicon** [comment]
I think we can move some files to separate folders.
Like `legacy`, `samples`, `unused`, etc.

**Comment by a1batross** [comment]
Another unused file: `voice_vgui_tweakdlg.cpp`.

**Comment by a1batross** [comment]
Not an issue actually, I used `exclude_files`.

`prop.cpp` is gone from master and that's fine I guess.
