### ISSUE TITLE
[MOD: Azure Sheep] На последнем кадре holster анимации, оружие снова промелькает в руках игрока перед тем, как он достанет новое оружие

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/hlsdk-portable#374]
Об этом баге сообщили в дискорде, используя лаунчер Azure Sheep для Android, но этот баг всё ещё актуален даже на свежих скомпилированных библиотеках с последними изменениями с этого репозитория.

Видео: https://media.discordapp.net/attachments/1106073125814280243/1106073126133039154/AzureSheep_20230511010904.mp4

**Comment by Vladislav4KZ** [comment]
Уточняю, я воспроизвёл этот баг на последнем билде нового движка.

А видео не моё, ссылка на него была скопирована с дискорда, там этот баг воспроизводился на старом движке.

**Comment by nekonomicon** [comment]
Под GoldSource баг воспроизводится?

**Comment by Vladislav4KZ** [comment]
> Под GoldSource баг воспроизводится?

Нет, на GoldSource не воспроизводится.
Проверял с библиотеками собранными с этого репозитория.
