### ISSUE TITLE
Отказ от хардкодинга максимального здоровья, патронов, брони игрока

### ISSUE THREAD

**Issue by Alex3474247** [FWGS/hlsdk-portable#382]
Даже в более старых движках, например Duke Nukem 3D, максимальный боезапас хранится в ресурсах игры в текстовом файле user.con, это был 1996 год, еще тогда программисты умели читать значения из ресурсов, а Half-Life вышел позже, в 1998, почему-то Valve решила это захардкодить. Данные параметры хранятся в  заголовочном файле weapons.h
Хотя я не думаю что это предложение очень актуально, видел при разработке для Андроида есть какие-то проблемы, но не стоит забывать про это. Хардкодинг данных параметров это древность, от этого желательно уйти. Это касается как оригинальной игры, так и модов/аддонов.

**Comment by a1batross** [comment]
Это было бы хорошо, но не уверен что это должно быть нашей целью. 

Если есть желание менять параметры, можно сделать это самостоятельно в своей собственной модификации.

**Comment by Velaron** [comment]
Мне кажется давно нужна отдельная репа или ветка под хотелки юзеров, в стиле Rofi DLL или чего там ещё

**Comment by a1batross** [comment]
Все хотелки не реализуешь, и даже если попытаешься это превратит код в
какую-то мешанину из кучи разрозненных маленьких фич.

SDK открыт для всех желающих, можно наконец начать работать над ним, писать
свои моды, познавать программирование.

**Comment by nekonomicon** [comment]
> Мне кажется давно нужна отдельная репа или ветка под хотелки юзеров, в стиле Rofi DLL или чего там ещё

И получить очередной XDM или PrimeXT.

**Comment by nekonomicon** [comment]
> а Half-Life вышел позже, в 1998, почему-то Valve решила это захардкодить. Данные параметры хранятся в заголовочном файле weapons.h

Многие студии из жадности старались спрятать в бинарник любые значения включая большие простыни текста, ну и HL не пример хорошо отлаженной игры, SDK выглядит сделанным наспех и не законченным.
Некоторые моддеры под HL тоже заявляют права на собственность и стараются все хардкодить, включая содержимое skill.cfg, например плюс являются противниками декомпиляторов ресурсов.
Вот то, что реально нужно - это унифицированный бот под любые HLDM-like моды практически без хардкода.

**Comment by Alex3474247** [comment]
Ну, моё дело предложить, а ваше отказаться, согласиться или отложить.

ср, 26 июл. 2023 г., 18:28 nekonomicon ***@***.***>:

**Comment by mittorn** [comment]
Xash Weapon System WHEN?
