### ISSUE TITLE
Does client library from opfor branch work?  (re: models are not showing)

### ISSUE THREAD

**Issue by sofakng** [FWGS/hlsdk-portable#390]
Does the client library from Opposing Force (opfor) branch work correctly?

I'm able to compile it successfully but when I play it then all of the models are missing.  However, if I use the client library from the master branch then Opposing Force seems to run correctly.

**Comment by nekonomicon** [comment]
Which build script was used?

**Comment by nekonomicon** [comment]
BTW I think this commit breaks something:
https://github.com/FWGS/hlsdk-portable/commit/8da76a8c3fb5246fb08526673f79f9a8d5498336
You can try to comment changes.
And yes, you need to use client and server libraries from `opfor` branch.

**Comment by a1batross** [comment]
This commit probably better be reverted. Optimizations completely broke animations, and I didn't have time to fix them myself, and @MoeMod didn't respond.

**Comment by sofakng** [comment]
Yep, that commit appears to be the problem.  If I disable the SIMD code then it works fine in both Opposing Forces and fixes the animation sutter/weirdness in Half Life.
