### ISSUE TITLE
[Opfor] У солдат есть оружие в случае, если поле weapon не прописано

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/hlsdk-portable#401]
Т. е. мапперы иногда умышленно не дают солдатам оружия, не прописывая в свойствах энтити поле weapon (видимо, равноценно должно работать, если поле есть, но прописано значение 0). Однако при этом в игре под портированными длл у солдат будет автомат, что нарушит задумку маппера и может повлиять на прохождение. Пример можно увидеть в моде https://www.moddb.com/mods/opposing-force-assault/downloads/opposing-force-assault-alpha-v1-demo, карта opcoverfire9.

**Comment by nekonomicon** [comment]
Исправлено в https://github.com/FWGS/hlsdk-portable/commit/5914b5779fdcbce33ea1b9c9d8ccaf91f0c30e24
