### ISSUE TITLE
[Opfor] Солдаты пытаются стрелять во врагов через бронированные стёкла

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/hlsdk-portable#402]
В норме, с оригинальными длл, солдаты не будут пытаться прострелить пуленепробиваемое стекло, а будут бегать вокруг, пытаясь выцелить противника с позиции, откуда в него реально можно попасть. Пример можно увидеть в моде https://www.moddb.com/mods/opposing-force-assault/downloads/opposing-force-assault-alpha-v1-demo , карта opcoverfire7. Там сначала надо убить зомби, хакнуть терминал, очутиться в капсуле. И дальше игрок ничего не делает, только наблюдает за происходящим, пока его не выпустят. Но с портированными длл солдаты бесконечно пытаются стрелять в противников сквозь бронированное стекло, не достигая результата.

**Comment by Qwertyus3D** [comment]
Не уверен, может ли это относиться к другим стреляющим монстрам, но не помешает сравнить, какие у кого условия атаки заданы.

**Comment by FreeSlave** [comment]
Посмотрел в декомпил опфора. Опфоровские солдаты действительно не пытаются стрелять через стекла, в отличие от халфовских.
Там есть и другие отличия (например, дистанция, с которой они начинают стрелять), но к этому возможно вернусь позже.

**Comment by nekonomicon** [comment]
Исправлено в https://github.com/FWGS/hlsdk-portable/commit/b22244139ceb5d20dc60fcce6ed730df908d034b
