### ISSUE TITLE
[Opfor] Game dll checks for multiplayer resources in singleplayer

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/hlsdk-portable#406]
Я использовал билд hlsdk-opforfixed-windows с модом Military Duty. Если не подключать fallback_dir "gearbox" с полным содержимым Опфора (что изначально не задумывалось автором), то длл жалуется на отсутствие мультиплеерных моделей в синглплеере. Т. е. в ситуации, когда ничто эти модели вызывать не должно. Причём список большой. Модели запрашиваются сразу при старте карты:
Error: models/flag.mdl couldn't load
Error: models/civ_stand.mdl couldn't load
Error: models/mil_stand.mdl couldn't load
Error: models/w_accelerator.mdl couldn't load
Error: models/w_backpack.mdl couldn't load
Error: models/w_fgrenade.mdl couldn't load
Error: models/w_icon.mdl couldn't load
Error: models/w_jumppack.mdl couldn't load
Error: models/w_porthev.mdl couldn't load

Звуки уже после сообщения, что уровень загружен:
Error: sound/ctf/bm_flagtaken.wav couldn't load
Error: sound/ctf/civ_flag_capture.wav couldn't load
Error: sound/ctf/itemthrow.wav couldn't load
Error: sound/ctf/marine_flag_capture.wav couldn't load
Error: sound/ctf/pow_armor_charge.wav couldn't load
Error: sound/ctf/pow_backpack.wav couldn't load
Error: sound/ctf/pow_big_jump.wav couldn't load
Error: sound/ctf/pow_health_charge.wav couldn't load
Error: sound/ctf/soldier_flagtaken.wav couldn't load
И после них опять повторно пытается прогрузиться список моделей.

Что-то типа стрёмной работы прекэша. Так-то на игру не влияет, но спамит ошибку на каждой загрузке карты, затрудняя проверку других ошибок в логе. Дллки Опфора не запрашивают всё это.

**Comment by FreeSlave** [comment]
Can we close it after the recent merge?

**Comment by Qwertyus3D** [comment]
Да, больше не спамит про эти модельки.
