### ISSUE TITLE
[Opfor] Black Ops Osprey do not spawn

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/hlsdk-portable#407]
Проблема давняя, со времён старого порта Опфора. Оспрей чёрных десов не спавнится на карте. Проверить можно в моде [Military Duty](https://www.moddb.com/mods/military-duty/downloads/military-duty-version-10-final), карта mil_duty15. После посещения командира в радиорубке здания у жд путей запускается скрипт спавна монстров, который начинается, по сценарию, с появления Оспрея чёрных десов, потом спавнятся все остальные, а в конце "манта" пришельцев должна подбить этот оспрей, который летает кругами и высаживает десов. Но на данный момент Оспрей не спавнится. Вероятно, что с этим связана ошибка в логе:
Can't find address: 5e481c4a
Error: Invalid function pointer in entity!

**Comment by nekonomicon** [comment]
Исправлено в https://github.com/FWGS/hlsdk-portable/commit/c417b06dbcca387b6b97498f49b54e6a6cf963bf
