### ISSUE TITLE
[Multiplayer] Ghost Hit Fix?

### ISSUE THREAD

**Issue by AFrameWorker** [FWGS/hlsdk-portable#409]
From the latest hl1 changelog:
>Improved client-side prediction to reduce "ghost shots". Like Counter-Strike, consider hitboxes and not just bounding boxes for hits on the client.

Will you implement this as well to hlsdk-portable? Would be very nice!

**Comment by nekonomicon** [comment]
Sure.

**Comment by FreeSlave** [comment]
I think we'll be looking into it only after they release the updated sdk.
It's also not clear if we should merge other changes. Mayeb keep them an option.

**Comment by nekonomicon** [comment]
Fixed in https://github.com/FWGS/hlsdk-portable/commit/acc38487957de49a53d356bc6f8ab5929ab71780
