### ISSUE TITLE
Does Half-Life, Opposing Force, and Blue Shift each need different client dlls?

### ISSUE THREAD

**Issue by sofakng** [FWGS/hlsdk-portable#417]
The difference branches (master, opfor, and bshift) each create different client dlls (client_arm64.dylib on macOS).

Does each game require these different versions or can a single version be shared between all of them?  (if so, which one?)

Thanks!

**Comment by a1batross** [comment]
There is a branch called `mobile-hacks` that has code for detecting simple mods and enabling their behavior. Currently, supported mods in that branch are here: https://github.com/FWGS/hlsdk-portable/blob/mobile_hacks/dlls/moddef.h

Opposing Force is quite complex to be included on this branch, as far as I know.

**Comment by nekonomicon** [comment]
Blue Shift's client has custom HUD color + we're [turn on fixes](https://github.com/FWGS/hlsdk-portable/blob/bshift/mod_options.txt) which required to use custom client too.

**Comment by sofakng** [comment]
Ahh OK -- No problem.  Thanks for the information.
