### ISSUE TITLE
[Bot 10] requires min_bots=1 not 0

### ISSUE THREAD

**Issue by d47081** [FWGS/hlsdk-portable#421]
Hello,

I found that without `min_bots` setting provided, server does not drop bots on players connections and lock access to players by `maxplayers` value.

It could be solved with `min_bots=1` setting but I can't set it to 0 and allow to drop all bots on real players join. Not sure that's bug or feature (with 0 as false interpretation)

**Comment by nekonomicon** [comment]
You can try to change condition here:
https://github.com/FWGS/hlsdk-portable/blob/bot10/dlls/client.cpp#L120
