### ISSUE TITLE
How to compile for cstrike/czero/czeror on arm64 linux

### ISSUE THREAD

**Issue by nickbailuc** [FWGS/hlsdk-portable#425]
I've got an M1 MacBook, trying to compile everything for the linux-arm64 target.

I know at least cs1.6 is possible as there exists (or used to be) binaries for android. The only place I found anything relevant was the [regamedll](https://github.com/FWGS/regamedll) repo, but it gives me some Java error I couldn't avoid (although I have the latest stable OpenJDK 17 installed).

From What I understand, cs1.6 requires some different process as it is not included in hlsdk (this repo) directly.

How can I compile the necessary cl_dlls and dlls (arm64.so) files?

**Comment by nekonomicon** [comment]
cs16client currently maintained by @Velaron:
https://github.com/Velaron/cs16-client

**Comment by nickbailuc** [comment]
> cs16client currently maintained by @Velaron: https://github.com/Velaron/cs16-client

What about TFC 1.5?

**Comment by nekonomicon** [comment]
And TF 1.5 too.
