### ISSUE TITLE
Where are the assets to `gravgun`

### ISSUE THREAD

**Issue by nickbailuc** [FWGS/hlsdk-portable#437]
From what I understand, `gravgun` is secretly the co-op mod. 

I can download and compile the `gravgun` branch, but it only creates an `hl.so`. AFAIK, there should be other files, like ones for the co-op menu. I found a few projects that seemed related on Moddb, but they were either for Android or Windows, while I'm running linux-arm64.

Is this what the Xash HL1 COOP servers use, or is there a different Xash compatible mod?

**Comment by nekonomicon** [comment]
> From what I understand, gravgun is secretly the co-op mod.

Не совсем.
Изначально это была первоапрельская шутка.
В Xash3D FWGS 0.17.0 выдавалась гравипушка в начале игры, в 0.17.1 ее убрали.
Потом выложили как отдельный мод с одной гравипушкой.
Позже еще добавили винтовку AR2 из HL2, ульту Gate of Babylon из Fate: Stay Night - Unlimited Blade Works и cockgun.
И кроме того уже предполагалось сделать пародию на HL2DM с бочками и унитазами + портированными картами из HL2DM.
Еще добавили модельку Нероны Клавдиус из игры Fate/Extella.
А кооперативный режим появился позднее.

Часть ассетов есть в [этом репозитории](https://github.com/nillerusr/gravgun-extras)
Остальные лучше спросить у @mittorn, хотя по идее все нужные ассеты должны скачиваться через fastdl в мультиплеере при заходе на кооп-сервера.
В любом случае за любые левые сборки и сервера мы не отвечаем, а они на данный момент все такие.
Мод находится в незаконченном состояниии и кооп вроде бы под новым движком не работает.

**Comment by nickbailuc** [comment]
> > From what I understand, gravgun is secretly the co-op mod.
> 
> Не совсем. Изначально это была первоапрельская шутка. В Xash3D FWGS 0.17.0 выдавалась гравипушка в начале игры, в 0.17.1 ее убрали. Потом выложили как отдельный мод с одной гравипушкой. Позже еще добавили винтовку AR2 из HL2, ульту Gate of Babylon из Fate: Stay Night - Unlimited Blade Works и cockgun. И кроме того уже предполагалось сделать пародию на HL2DM с бочками и унитазами + портированными картами из HL2DM(из них портирована только dm17). Еще добавили модельку Нероны Клавдиус из игры Fate/Extella. А кооперативный режим появился позднее.
> 
> Часть ассетов есть в [этом репозитории](https://github.com/nillerusr/gravgun-extras) Остальные лучше спросить у @mittorn, хотя по идее все нужные ассеты должны скачиваться через fastdl в мультиплеере при заходе на кооп-сервера. В любом случае за любые левые сборки и сервера мы не отвечаем, а они на данный момент все такие. Мод находится в незаконченном состояниии и кооп вроде бы под новым движком не работает.

А как тогда можно запустить ЛАН сервер в СООР?

**Comment by nekonomicon** [comment]
На старом движке.
Лучше для этой цели использовать [форк тябуса](https://github.com/tyabus/xash3d)

**Comment by nickbailuc** [comment]
> На старом движке. Лучше для этой цели использовать [форк тябуса](https://github.com/tyabus/xash3d)

но где достать сами фаилы чтобы запустить LAN multiplayer но в campaign mode?

**Comment by mittorn** [comment]
The main feature is valve/ggm subdir which contains custom menus and 
player settings/registrations.

It use filesystem as DB

Server allows migrating players during restart, saving multiplayer 
state. Players will reconnect and spawn in saved places with same 
weapons they have before restart

Example menus for Trash server can be found here:

http://mittorn.fwgs.ru/ggm/

Coop menus are mostly integrated into hl.so, but you can override it 
partially placing "coopmenu" entry for menu dir.

"init" menu also was used in coop

Example public config from trash server, old engine:

```
set sv_zmax 3300
set sv_nat 0
set port 27022
set mp_ar2_mp5 1
set mp_allow_ar2 0
set mp_allow_gravgun 1
set mp_coop 0
set mp_coop_changelevel 0
set mp_coop_nofriendlyfire 0
set mp_gravgun_players 0
set mp_enable_ar2 1
set mp_enable_gravgun 1
set sv_cheats 0
set sv_enttools_enable 0
set mp_enttools_enable 1
set mp_enttools_players 0
set mp_checkentities 1
mp_enttools_clearblacklist
mp_enttools_addblacklist * 40 0
mp_enttools_addblacklist monster_ 20 0
mp_enttools_addblacklist monster_gargantua 2 1
mp_enttools_addblacklist monster_nihilanth 0 1
mp_enttools_addblacklist worldspawn 0 1
mp_enttools_addblacklist player 0 1
mp_enttools_addblacklist falldamage 0 1

mp_enttools_lockmapentities 1
set maxplayers 32
set hostname "Trash"
set public 1
set sv_downloadurl "http://mittorn.the-swank.pp.ua/"
set sv_allow_download 1
set sv_allowdownload 1

set mp_allowmonsters 1
set fps_max 60
set sv_unlag 0
set sv_maxpacket 1400
set mp_flashlight 1
set sv_validate_changelevel 0
set sv_clientclean 0
set mp_coop_reconnect_hack 0
set mp_unduck 1
set mp_semclip 0
pausable 1
sv_pauseable 1
set host_mapdesign_fatal 0
set mp_coop_noangry 0
set mp_spectator 1
set defaultmap brush_sample_box_03
mp_touchname "ENT MENU"
mp_touchcommand "entity_main;cmd_scripting 1"
mp_enttools_checkowner 2

exec banned
exec listip
```
It still do not have docs. Partially it was on wiki, but mostly it lost, 
i do not remember why

ggm still does not support new engine, many features may be broken, 
movetype hack breaks any npc interpolation

most features require allowing save in multiplayer, which was never done 
in new engine branch

Generally, ggm branch now has broken git history breaking any rebases to 
master branch and needs much work to fix that, so i stopped updating it 
until rebase and have no much time for rebase :(

**Comment by mittorn** [comment]
For coop-related config, it might be found here:

https://github.com/FWGS/hlsdk-portable/blob/gravgun/README.ggm.md

Existing coop servers may have extra patches and may use diffrent branches.

Some maps using entpatches to prevent player stucks and cycle game in 
end, but it's pure optional:

http://mittorn.fwgs.ru/coop-entpatches/
