### ISSUE TITLE
Не могу заставить cmake собрать код для Linux x86-64, а waf не работает

### ISSUE THREAD

**Issue by ArtemS2** [FWGS/hlsdk-portable#438]
Автоматом только 32-битный код предлагает(

**Comment by ArtemS2** [comment]
Хочу собрать DMC

**Comment by ArtemS2** [comment]
@nekonomicon  Спасибо , все получилось, но почему-то сервер с xashds не виден мастер серверу, однако прямое соединение по ip работает.

**Comment by nekonomicon** [comment]
Я думаю, это уже не проблема hlsdk-portable.
