### ISSUE TITLE
Not linking to libdl when building with waf

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#442]
Running

```
./waf configure -T release
./waf
```

I'm getting error messages like this:

```
build/../cl_dll/input_goldsource.cpp:1614: undefined reference to `dlsym'
build/../cl_dll/input_goldsource.cpp:1616: undefined reference to `dlerror'
build/../cl_dll/input_goldsource.cpp:1620: undefined reference to `dlerror'
```

If I remove this check it gets built fine
https://github.com/FWGS/hlsdk-portable/blob/19f3e9197854f4bfbd3cf63bcead19439275f926/wscript#L178-L179

Looks like something wrong with the order in which `env.GOLDSOURCE_SUPPORT` is assigned and checked.

**Comment by a1batross** [comment]
ACK

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/hlsdk-portable/commit/09a158f2e77c6b6985a28937f23d4d1073cc80dd
