### ISSUE TITLE
Increase crosshair size/decrease opacity on high-res

### ISSUE THREAD

**Issue by nickbailuc** [FWGS/hlsdk-portable#445]
Im playing (mostly multiplayer and mods) on a tiny 13 inch screen at 2560x1600 and can barely see the crosshair. For some weapons like the revolver, can't see it at all.

Is there a way to make the crosshair more solid and larger? I've tried the `font` console commands but they don't really help. I can increase HUD size, but it doesn't make the crosshair easier to notice.

Is there a way to make the crosshair static, white, no opacity at all, or something like that in Xash?

**Comment by SNMetamorph** [comment]
You can use `hud_scale` console variable to adjust HUD size as you want

**Comment by nickbailuc** [comment]
> You can use `hud_scale` console variable to adjust HUD size as you want

I know, I tried that already. It doesn't seem to change the size of the dots (for example in the SMG, the dots are still often too small to notice in combat) at least on my smaller screen, and being a transparent orange doesnt help. Even setting `hud_scale 5`, still not great, but makes everything else too large.

It'll expand the distance between the dots in the crosshair, but not much to the size of the dots themselves

**Comment by nickbailuc** [comment]
![Screenshot_2024-03-15_14 23 54](https://github.com/FWGS/hlsdk-portable/assets/35620734/c41182e4-2eda-4dea-8377-951e448011a6)

I mean look at this, it really blends in with a lot of HL backgrounds, and the rest of the HUD is stupid big

**Comment by nickbailuc** [comment]
![Screenshot_2024-03-15_14 26 15](https://github.com/FWGS/hlsdk-portable/assets/35620734/af1685cc-b013-4b22-8738-b59c93c31e5c)

I usually play at `hud_scale 1.5`
do you see the crosshair in this image?

**Comment by a1batross** [comment]
I do NOT recommend using fractional scale. Use integer values like 2 or 3.

Also, you can mod the crosshairs. There is a lot of custom crosshairs on
sites like gamebanana.

**Comment by nekonomicon** [comment]
@nickbailuc I think with such basic questions you can visit forums like twhl.info/hlfx.ru/cs-mapping.com.ua or our discord servers.
