### ISSUE TITLE
Возможно ли собрать под Windows XP

### ISSUE THREAD

**Issue by Artem-coderh** [FWGS/hlsdk-portable#452]
У меня есть Microsoft Visual studio 6, Windows XP Professional x86 SP3.

**Comment by nekonomicon** [comment]
Да.

> Microsoft Visual studio 6

Для этих целей лежат скрипты compile.sh, но для модов их никто не обновлял так как особой надобности уже нет.

ЕМНИП на Windows XP должны работать Visual Studio 2012/2013/2015, а там с использованием waf и cmake никаких проблем не должно быть.

Также можно использовать mingw, но не рекомендуется, потому что GoldSrc не поддерживает декорацию имён gcc.

**Comment by FreeSlave** [comment]
> Для этих целей лежат скрипты compile.sh

compile.bat

Инструкции для сборки с VS6 есть в ридми проекта. Но мы регулярно не проверяем актуальность этого батника.

**Comment by mittorn** [comment]
mingw для 32битных сборок может нормально не заработать пока не 
проставлены аттрибуты выравнивания стека
Так же была проблема с aggregate return, которая даже в visual studio 
могла вызывать проблемы.

А какие проблемы с поддержкой windows xp на современных VS?
Я знаю, что exe не запускаются, но ведь hlsdk это dll
По идее если отключить неявную вставку TLS на статиках (на XP 
LoadLibrary не инициализирует TLS релокации), должно работать при 
статической линковке CRT

**Comment by a1batross** [comment]
@mittorn 

Нет, mingw это совсем дохлая идея. Тут @nekonomicon прав насчёт mingw. Оно может и "заработает", но существующие сохранения не будут работать. Как и последующие, но собранные другим компилятором. Тем более GoldSrc непредсказуемо может отреагировать на такой манглинг в GCC.

В старом ксаше это когда-то работало, так как там не было этого механизма разбора манглинга для кроссплатформенных сейвов. Я его сделал как раз в новом.

**Comment by a1batross** [comment]
Оказывается было достаточно включить vcs_info.cpp и оно вполне собирается. https://github.com/FWGS/hlsdk-portable/commit/3229067f78ee62097eb59d927fb4c552afed800c 

Под Win32 ксашем работает, под голдсорсом не проверял.
