### ISSUE TITLE
Player's camera moves after the VGUI MOTD gets closed 

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#454]
1. Create motd.txt with some text
2. Start a multiplayer game
3. Press OK on motd window with a mouse
4. The camera is instantly turning to the different angle

**Comment by a1batross** [comment]
Not only that, I think it's possible to move in the intermission screen. It's one of the oldest bugs that has been caused by either early engine or SDK changes, or even both.

**Comment by FreeSlave** [comment]
I don't have such bug on Windows btw
