### ISSUE TITLE
makefont

### ISSUE THREAD

**Issue by porloc** [FWGS/hlsdk-portable#46]
Привет. Скидываю исправленный makefont.
[makefont.zip](https://github.com/FWGS/hlsdk-xash3d/files/1642715/makefont.zip)

**Comment by porloc** [comment]
потому что isprint работает только с латиницей и символы локализации он не пропускает.

**Comment by porloc** [comment]
это проверка там излишняя потому что все коды непечатываемых-управляющих символов находятся до 32 и мы их так и так пропускаем, потому что начинаем печатать с 32 символа.

**Comment by porloc** [comment]
круто, теперь мой код на гитхаб

**Comment by mittorn** [comment]
У меня это сгенерировало шрифт в cp1252

**Comment by mittorn** [comment]
Так же в репе нет cmdlib без которого невозможно скомпилировать этот код. Желательно конечно сделать новый makefont на основе шрифтрендера mainui_cpp с подобной настройкой. Сделал шрифт для маленького экрана (128x160) - так пришлось патчить выходной файл чтобы убрать лишние пиксели по бокам, откалибровать высоту

**Comment by nekonomicon** [comment]
Вообще все тулзы из HLSDK желательно портировать под *nix.

**Comment by mittorn** [comment]
makefont можно сделать из менеджера шрифтов. fnt лумп состоит из структуры qfont и bmp данных

**Comment by mittorn** [comment]
Только там ограничение на ширину в 256. То есть придётся ограничить ширину атласа в 256
