### ISSUE TITLE
Bhopcap неработает

### ISSUE THREAD

**Issue by Elinsrc** [FWGS/hlsdk-portable#465]
Квар mp_bhopcap не работает, думаю проблема появилась после этого комита https://github.com/FWGS/hlsdk-portable/commit/aec0f79806cacdb1861758ade170d33e75f9c8b1

**Comment by nekonomicon** [comment]
А как ты его проверял?
Сейчас значение переключается для игрока только после следующего респауна.

**Comment by Elinsrc** [comment]
менял значение квара и делал рестарт

**Comment by a1batross** [comment]
Как минимум у меня на сервере bhopcap отключен, и всё работает, и предиктится нормально.

**Comment by Elinsrc** [comment]
Исправил проблему, дело было в кривом плагине, который ограничивал скорость
