### ISSUE TITLE
[BUG?] Why is github actions job's Linux vgui build's client.so being hardlinked to /home/runner/.../lib/vgui.so?

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/hlsdk-portable#483]
When I tried to run xash3d with prebuilt linux vgui build from github actions job, error pop-up about client.so with that text
`client.so: /home/runner/work/hlsdk-portable/hlsdk-portable/vgui_support/vgui-dev/lib/vgui.so: no such file or folder`

**Comment by a1batross** [comment]
It's a bug of an ancient binutils version used in Steam Runtime Scout.

See https://github.com/FWGS/hlsdk-portable/pull/481

**Comment by TheKingFireS** [comment]
Oh okay, thanks for answer.
