### ISSUE TITLE
Artifacts for Win32 wrongly include .lib files

### ISSUE THREAD

**Issue by a1batross** [FWGS/hlsdk-portable#486]
Engine or users don't need .lib files for neither client or server DLLs.

These files shouldn't be shipped.

**Comment by FreeSlave** [comment]
Do .lib files provide any value when built in Debug mode? (asking for manual build where you can choose Debug).

**Comment by a1batross** [comment]
Nope. When compiling DLLs, they only contain a list of exported functions and it's addresses.
