### ISSUE TITLE
Satchel can incorrectly appear in HUD

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-portable#494]
If player has thrown all his satchels and died (i.e. when satchel in the "radio" state), the weaponbox spawns with no satchels. Then the other player (or the same one after he respawns) can take this weaponbox and satchel will appear in HUD despite having 0 ammo.

In anniversary Half-Life satchel won't appear in HUD in this case.

**Comment by FreeSlave** [comment]
Found the code https://github.com/ValveSoftware/halflife/blob/b1b5cf5892918535619b2937bb927e46cb097ba1/dlls/player.cpp#L831-L842

**Comment by a1batross** [comment]
Never liked this logic in HLDM. The logic solution would be giving the player who picked up that weaponbox a radio, so they could blow up other dead player's satchels, but instead it's kept in that weird state of giving player nothing, while also not letting blow up satchels. There was even a way to spam the level with satchels, blocking players on spawn.

I guess not packing satchels into weaponbox just to not show them in HUD also works but the glitched logic is still there.
